### ISSUE TITLE
.bin files missing

### ISSUE THREAD

**Issue by InesArous** [minhaoJ2/TaxoEnrich#3]
Thanks for publishing your code! 
For the datasets you are using, the .bin files are missing in MAG-PSY, Semeval-Noun and Semeval-Verb. For MAG-CS dataset, I get UnpicklingError: pickle data was truncated. 
Could you please update your dataset folders?
Thanks!

**Comment by minhaoJ2** [comment]
Please follow the instructions in the README file to generate the other files. In MAG-CS, the bin file was corrupted due to some unknown reason on Github. Please re-run the generate_binary_dataset.py as instructed in README. Then the bin file should work.

**Comment by wiersmalab** [comment]
Using the following files:

computer_science.taxo
computer_science.terms
computer_science.terms.embed

And running

python generate_dataset_binary.py --taxon_name computer_science --data_dir ./data/MAG_CS --existing_partition 1 --partition_pattern internal

Results in the following error:

(venv) wiersmalab@wiersmalab-titan:~/Projects/TaxoEnrich$ python generate_dataset_binary.py --taxon_name computer_science --data_dir ./data/MAG_CS --existing_partition 1 --partition_pattern internal
Using backend: pytorch
/home/wiersmalab/Projects/TaxoEnrich/venv/lib/python3.8/site-packages/dgl/base.py:45: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  return warnings.warn(message, category=category, stacklevel=1)
Loading terms: 29654it [00:00, 251742.45it/s]
Loading relations: 46248it [00:00, 319981.94it/s]
Loading embedding ...
Traceback (most recent call last):
  File "generate_dataset_binary.py", line 19, in <module>
    main(args)
  File "generate_dataset_binary.py", line 5, in main
    binary_dataset = MAGDataset(name=args.taxon_name, path=args.data_dir, embed_suffix=args.embed_suffix, raw=True,
  File "/home/wiersmalab/Projects/TaxoEnrich/data_loader/dataset.py", line 146, in __init__
    self._load_dataset_raw(path)
  File "/home/wiersmalab/Projects/TaxoEnrich/data_loader/dataset.py", line 214, in _load_dataset_raw
    embeddings = KeyedVectors.load_word2vec_format(embedding_file_name)
  File "/home/wiersmalab/Projects/TaxoEnrich/venv/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 1547, in load_word2vec_format
    return _load_word2vec_format(
  File "/home/wiersmalab/Projects/TaxoEnrich/venv/lib/python3.8/site-packages/gensim/models/utils_any2vec.py", line 288, in _load_word2vec_format
    _word2vec_read_text(fin, result, counts, vocab_size, vector_size, datatype, unicode_errors, encoding)
  File "/home/wiersmalab/Projects/TaxoEnrich/venv/lib/python3.8/site-packages/gensim/models/utils_any2vec.py", line 220, in _word2vec_read_text
    raise ValueError("invalid vector on line %s (is this really the text format?)" % line_no)
ValueError: invalid vector on line 1080 (is this really the text format?)
